name: asn-bot
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Python script
      run: python3 convert_rule.py
    - name: Run Python script2
      run: python3 convert_rule2.py
    - name: Check changes
      id: check_changes
      run: |
          if git diff --name-only; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
    - name: Commit files
      env:
          GITHUB_TOKEN: ${{ secrets.action_bot }}
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.name 'action-bot'
        git config --global user.email 'xiaoleigs@gmail.com'
        git add .
        git commit -m 'update by bot'
        git push
