name: asn-bot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Comment about changes we can't accept"
        env:
          GITHUB_TOKEN: ${{ secrets.action_bot }}
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Python script
      run: python3 convert_rule.py
    - name: Run Python script2
      run: python3 convert_rule2.py
    - name: Commit files
      run: |
        git config --global user.name 'action-bot'
        git config --global user.email 'xiaoleigs@gmail.com'
        git add .
        git commit -m 'Update files'
        git push
